name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

env:
  GITLINK: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-linux.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
      continue-on-error: true
    - uses: actions/upload-artifact@v2
      with:
          name: my-artifact
          path: /home/runner/.local/share/code-server
